timeout: 1

/EquinoxOS
    protocol: limine
    path: boot():/kernel.elf
    module_path: boot():/logo.bmp
    module_path: boot():/app.elf
    module_path: boot():/hello.txt
    module_path: boot():/doom1.wad
    module_path: boot():/doom.bin
    architecture: x86_64